version: '2'

services:
  ovip-db:
    image: mysql:latest
    container_name: ovip-db
    environment:
      - MYSQL_ROOT_PASSWORD=ovip
      - MYSQL_USER=ovip
      - MYSQL_PASSWORD=ovip
      - MYSQL_DATABASE=ovip

    volumes:
      - ./persistant/mysql:/var/lib/mysql

    ports:
      - "3306:3306"

  dbclient:
    image: mysql:5.5
    container_name: dbclient
    links:
      - ovip-db

    #command: sh -c 'exec mysql -hmysql -P3306 -uovip -povip'

  # official-vip:
  #   image: ovip
  #   container_name: official-vip
  #   environment:
  #     - PHPMYADMIN_PW=ovip
  #     - DB_USER=ovip
  #     - DB_PASSWORD=ovip
  #     - DB_DATABASE=ovip
  #     - DB_HOST=ovip
  #     - DB_PORT=3306

  #   volumes:
  #     - ./persistant/app:/app

  #   links:
  #     - ovip-db

  #   ports:
  #     - "80:80"

    #command: bash -c 'cd /app/build/ && ant configure && ant build-unit'