ovip-db:
  image: mysql:5.5

  environment:
    - MYSQL_ROOT_PASSWORD=shopware
    - MYSQL_USER=shopware
    - MYSQL_PASSWORD=shopware
    - MYSQL_DATABASE=shopware
  # volumes:
  #  - /var/lib/docker/persistent-volumes/shopware/db:/var/lib/mysql

dbclient:
  image: mysql:5.5
  links:
   - ovip-db:mysql
  command: sh -c 'sleep 10000; mysql -h"$$MYSQL_PORT_3306_TCP_ADDR" -P"$$MYSQL_PORT_3306_TCP_PORT" -ushopware -pshopware'
  # command: sh -c 'exec mysql -hmysql -P3306 -ushopware -pshopware'
  # command: sh -c 'ping mysql'

shopware:
  image: ovip
  environment:
    - PHPMYADMIN_PW=bitte_aendern
    - DB_USER=shopware
    - DB_PASSWORD=shopware
    - DB_DATABASE=shopware
    - DB_HOST=shopwaredb
    - DB_PORT=3306
  # volumes:
  #  - /var/lib/docker/persistent-volumes/shopware/shopware/var/www/html:/var/www/html
  links:
   - ovip-db:shopwaredb
  ports:
   - "8000:80"
